services:
  web:
    build: frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
  api:
    build: backend
    ports:
      - 8081:8080
    volumes:
      - ./go-cache:/root/.cache/go-build
      - ./backend:/app
      - ./data:/data